#:kivy 1.0.0

<MyGrid>:
    GridLayout:
        height: root.height - 25
        width: root.width - 25

        canvas:
            Rectangle:
                pos: self.center_x - 5,0
                size:10, self.height
        Label:
            font_size: 70
            center_x: root.width / 4
            top: root.top - 50
            text: "0"
        Label:
            font_size: 70
            center_x: root.width * 3/4
            top: root.top - 50
            text: "0"